###query user
GET http://192.168.17.234:8081/api/user

###create user
POST  http://192.168.17.234:8081/users HTTP/1.1
Content-Type: application/json

{
    "username": "{{$guid}}",
    "password": "5345435"
}